### ISSUE TITLE
ui: add grouping of nodes according to metadata field(s)

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1544]
in the k8s setup I would like to be able to group all nodes which have the same metadata value - for example in the bookinfo sample example I would like to group according to:

```
K8s.Labels.app
```

Such that all elements that have `app=reviews` are clustered together (pods, deployments, networkpolicy)

**Comment by pierrecregut** [comment]
This could have other uses if it was accessible to the end-user (eg through workflows). I have a similar need to answer a question from internal users. To handle high availability a lot of elements (virtual or physical ie fabric) are duplicated. The result is a topology very hard to understand. They would like to be able to group the duplicates (eg interfaces in a LAG). 

This makes the ownership relation more dynamic with the risk of having dags or even arbitrary graphs instead of a forest, if the nodes do not share the same parent.

Another problem I see is the virtual node that incarnates the group for D3JS. We probably want to keep it out of the real graph so that  algorithms walking through the graph are not disrupted.

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui
Feel free to create feature request there
