### ISSUE TITLE
icmpv4 injected packets have ip_header[time_to_live] = 0

### ISSUE THREAD

**Issue by nbratman** [skydive-project/skydive#1570]
=> they are dropped on the way and never arrive their destination
tcpdump output on the sender side:
![image](https://user-images.githubusercontent.com/26632729/50780398-7c8f8980-12ab-11e9-8d35-131070e0646d.png)
tcpdump on the receiver side is empty

**Comment by safchain** [comment]
@nbratman thanks for reporting this. Do you plan to submit a patch or do you want us to fix it ?

**Comment by nbratman** [comment]
@safchain Honestly I don't know how to fix this, or where in the code to look, but If you can point me in the right direction I can try

**Comment by safchain** [comment]
@nbratman it should be easy :)

here is where the icmp is generated : 
https://github.com/skydive-project/skydive/blob/master/packetinjector/forge.go#L69

You will see that the TTL is not provided. But if take a look at the tcp packet generation you will see that the TTL is set : 
https://github.com/skydive-project/skydive/blob/master/packetinjector/forge.go#L88

So it just matter of providing as it is for tcp.

Let me know if you want and have time to work on it :) otherwise I'll do it. Thanks.

**Comment by nbratman** [comment]
@safchain but I'm new to Skydive, so I think if you could do that instead it would be more correct and efficient

**Comment by nbratman** [comment]
@safchain https://github.com/skydive-project/skydive/pull/1571

**Comment by lebauce** [comment]
Fixed by https://github.com/skydive-project/skydive/pull/1571
