### ISSUE TITLE
Agent auto-deployment/auto-update feature.

### ISSUE THREAD

**Issue by kdorfman** [skydive-project/skydive#178]
Suppose one have huge skydive agent install running over many hosts, then process of upgrade (copy new skydive binary and re-start it) should be done automatically using skydive analyzer (as it has knowledge about every active agent).

Lets discuss and define requirements and design for this:
- introduce skydive agent instance version
- implement skydive analyzer flow to be able to copy new binary to every host running agent
- remote agent restart initiated from analyser

Any ideas?

**Comment by kdorfman** [comment]
Overseer is a package for creating monitorable, gracefully restarting, self-upgrading binaries in Go (golang): https://github.com/jpillora/overseer

**Comment by nplanel** [comment]
+1 for Overseer, It's was on our old backlog not as priority
Normally we should deploy from the Analyzer as the Agent(s) can pull the upgrade over ... It would be the orchestrator of the remote upgrade as well.

**Comment by safchain** [comment]
So I think there is several thing to do as Konstantin started to explain : 

We wanted to introduce a config API, in order to be able to get info about the running configuration, like agent version, getting current config parameter, etc.

I'm ok that analyzer should do the update job, but I think we should first have the "multiple analyzer support" (BTW started to work on it). 

So I Think we should open an issue for the config API ?

**Comment by lebauce** [comment]
The config API has been introduced.

Regarding the auto-deployment/auto-update, it's probably way too complicated to implement
