### ISSUE TITLE
Question: How does the Web-Login work?

### ISSUE THREAD

**Issue by TheHADILP** [skydive-project/skydive#1800]
I set up Skydive with docker-compose.
When I visit the WebUI I am already logged in.
I can log out but on the Login page I can enter any combination of username and password and get logged in.
Since I want to configure the WebUI to be accessible remotly, this is not really ideal.

Did I miss something? How do I configure the Authentication?

**Comment by safchain** [comment]
By default there is no authentication. In order to set it you have to fill some parameters in the config file:

First you need to specify a name for your authentication backend :
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L55

Then you need to define this backend : 
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L401

Skydive supports two mode, `basic` and `keystone`. `basic` is a standard http basic auth mechanism, thus the passwords can be generated with `htpasswd`

For example config file with an admin user could be like this:

````
analyzer:
  auth:
    api:
      backend: mybackend

auth:
  mybackend:
    type: basic
    users:
      admin: supersecret
```

With this configuration the users a defined within the config file. Please note you can use an external file
to define them:
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L406

**Comment by safchain** [comment]
Closing it for now, please re-open if needed
