### ISSUE TITLE
Incorporate event information from sysdig 

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1888]
sysdig (via its' underlaying libraries) is an alternative to strace/dtrace which captures a wide range of events: network, file, etc.

https://sysdig.com/blog/sysdig-vs-dtrace-vs-strace-a-technical-discussion/

we may consider  a representation along the lines of what has  been done in socketinfo., If so then we would represent the information as topology in which a process and a file are graph nodes, access of a process to a file is represented as a link ... this information changes according to current state so link exists between file open() ... and is deleted on file close()

An altenative representation is to view information in a similar why that flows are, in which all operations between open() to close() are grouped into a single "flow".

**Comment by davidhIBM** [comment]
Quick first comments... 
There are security significant and important use cases for such collection as I will detail below. From a security standpoint, ideally one will have a single telemetry system that will be extendiable and collect all the necessary telemetry needed for security analytics. From an admin point of view, this also allows deeper understanding of the endpoints of the network (the process that sent the traffic and its behaviour). 

Security use cases can be divided into:
1. Monitoring access to sensitive files
2. Monitoring significant or specific changes in the normal process behaviour (in combination to a change in network behaviour or not)
3. Monitoring the use of certain indicative system calls (e.g. patterns aligned with bitcon mining, in combination to a change in network behaviour or not)
4. Comparing the behaviour of one process from a set with others of the same set (running on the same node or on other nodes in the cluster). 

For such use cases, getting summarisation of which process used which system calls (+parameters of such system calls) can be similar to the collection and reporting of network flows. This sounds like a reasonable first step. 

Future topology views can be added to contextualise the information and as a basis for visualisation of the data:
1.  Showing what the process does now
2. Showing what the process has been doing since it started
3. Identifying changes in the process behaviour - report the first time a process did something new
4. Identifying how the process compare to his set 
etc.

hope this helps.

**Comment by davidhadas** [comment]
Quick first comments...
There are security significant and important use cases for such collection as I will detail below. From a security standpoint, ideally one will have a single telemetry system that will be extendiable and collect all the necessary telemetry needed for security analytics. From an admin point of view, this also allows deeper understanding of the endpoints of the network (the process that sent the traffic and its behaviour).

Security use cases can be divided into:

Monitoring access to sensitive files
Monitoring significant or specific changes in the normal process behaviour (in combination to a change in network behaviour or not)
Monitoring the use of certain indicative system calls (e.g. patterns aligned with bitcon mining, in combination to a change in network behaviour or not)
Comparing the behaviour of one process from a set with others of the same set (running on the same node or on other nodes in the cluster).
For such use cases, getting summarisation of which process used which system calls (+parameters of such system calls) can be similar to the collection and reporting of network flows. This sounds like a reasonable first step.

Future topology views can be added to contextualise the information and as a basis for visualisation of the data:

Showing what the process does now
Showing what the process has been doing since it started
Identifying changes in the process behaviour - report the first time a process did something new
Identifying how the process compare to his set
etc.

...hope this helps.

**Comment by hunchback** [comment]
@davidhadas being able to identify changes in a processes state suggests we may want to use the topology representation. Can you elaborate what metrics may be relevant? (such as the number of open file descriptors)

**Comment by hunchback** [comment]
will reopen once relevant
