### ISSUE TITLE
Use UTC times

### ISSUE THREAD

**Issue by lebauce** [skydive-project/skydive#199]
Right now, we use time.Now(), convert it to epoch and store it into the database.
We should use UTC time instead

**Comment by nplanel** [comment]
from golang pkg time :

Unix() returns the local Time corresponding to the given Unix time, sec seconds and nsec nanoseconds since January 1, 1970 UTC.

So we didn't need to apply UTC() on time.Unix() but on other bits around like graph/traversal  ex : time.Now()  need to be converted to time.Now().UTC()

**Comment by masco-enovance** [comment]
https://softwarefactory-project.io/r/#/c/6146/
