### ISSUE TITLE
Couldn't create node with same name?

### ISSUE THREAD

**Issue by whl739** [skydive-project/skydive#2197]
I use python api to create topology, and found that it couldn't create node with same name, since the two different switches have same port name.

And another thing is the return value of `client.noderule_create` has no `TID` but a `UUID`, when i query `G.V().Has('TID', 'uuid')`, there's nothing returned.

But the host node which created by agent has same `eth0`, `eth1`, why these can be created? Did i miss something?

**Comment by safchain** [comment]
I would rather use the websocket API that will allow you to specify an ID instead of using the Name. You can see an example here:
https://github.com/skydive-project/skydive/blob/master/contrib/python/api/samples/inject-nodes1.py

**Comment by whl739** [comment]
What does the `host` mean in [`GraphElement`?](https://github.com/skydive-project/skydive/blob/d81a665ddebd763167fb9780000b7ad7ff059cba/contrib/python/api/skydive/graph.py#L23)

**Comment by whl739** [comment]
I have successfully created the topology by websocket api, but the strange thing is that when i restart the `analyzer`, the topology is missing.

**Comment by safchain** [comment]
Sorry that is something I didn't mention but the way the websocket API is working is more or less how the agent communicates with the analyzer, so this is something which is not persistent and the client has to re-inject if the analyzer is stopped. I'll have a look at the issue you have with the node/edge-rules so that you could use it.

**Comment by whl739** [comment]
Thanks for your kind help, i'll close this issue.
