### ISSUE TITLE
Simplify adding new probes

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2214]
Would be nice to have a more straighforward approach to add new probes.

Maybe is it possible to copy how Telegraf handles it.
They add a new folder with the "plugin" plus an import in a file with all the plugins: https://github.com/influxdata/telegraf/pull/7418/files

They relay in the "init()" function of each folder to register the plugin.

**Comment by lebauce** [comment]
We thought about using this approach (instead of calling the Register function manually here https://github.com/skydive-project/skydive/blob/master/agent/topology_probes.go#L48-L60). But, if I remember correctly, we thought it was more explicit to call the Register function than relying on an unnamed import like `import _ "github.com/skydive-project/skydive/topology/probes/docker"`
