### ISSUE TITLE
Dynamic vs. static placement on high scale environments

### ISSUE THREAD

**Issue by liranschour** [skydive-project/skydive#229]
After simulations of high scale environments (100 nodes) with the current JS d3 force layout. I came to the conclusion that we might want to statically place some of the elements in order to show a more coherent topology graph. (it will also help in the aspect of performance but my focus was clarity of visualization).

We have an abstraction of layers in our topology that we can use. For example I tried to put in circles the following layers: edge fabric (fabric node which is connected to a host), hosts, namespaces. Each layer is defined with a specific radius which defines the static (fixed) place of each node in the layer.

I believe that this kind of approach will enhance the clarity of the visualization and will also show a reduction in computation.

**Comment by safchain** [comment]
HI,

I have a WIP that could help, adding nested force layout support, one per group, so that there is no overlapping anymore between groups and the constraint calculation is reduced. I didn't test too much so far. The statics placement is a good idea, we could place groups on the circle depending on the level. I'll try to push something testable next week.

**Comment by liranschour** [comment]
Great. I will be happy to look on it. I tried myself few sketches with the code end ended up with the conclusion I wrote above.

**Comment by safchain** [comment]
Close it for now, will be addressed by  #1730
