### ISSUE TITLE
Add route table probe

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#354]

**Comment by masco-enovance** [comment]
what are the fields need to displayed in this route struct https://github.com/vishvananda/netlink/blob/0872fbf3015e21e760f71debd11379a9daf7abcc/route.go#L29

**Comment by safchain** [comment]
I think to start we can have something simple like

table int
prefix net.IP
nexthops []net.ip

**Comment by eonpatapon** [comment]
Are you planning to add the route table to the node properties ?

**Comment by safchain** [comment]
@eonpatapon yes that's the plan and then we will add a layer3 topology layer
https://github.com/skydive-project/skydive/pull/380

**Comment by nlewo** [comment]
We are working on adding notification mecanisms in OpenContrail to expose route information. This is in progress but we can still provides some information regarding the structure of a route.
Basically, datas that we would like to take into account are:
- route family: ip4', ipv6, bridge
- prefix length
- address
- some flags
- nexthop: this can be a little bit complex since it can contain a encapsulation type, nexthop IP, nexthop interface...
- mpls label

I could provide more details (and OpenContrail driver implementation) when tooling is available in Contrail.

**Comment by lebauce** [comment]
Fixed by https://github.com/skydive-project/skydive/pull/380
