### ISSUE TITLE
Deadlock when ElasticSearch is slow

### ISSUE THREAD

**Issue by vperelmax** [skydive-project/skydive#636]
Lately in one of our test cases found this bug.
The system becomes frozen, WebUIs that disconnect - are not really disconnected and we with "client status" continue seeing them, through WebUI we stop seeing any topology.
And when we kill the analyzer with "kill -QUIT <pid>" and look at its log we see that many threads hold on lock of Graph, and here is the main reson - not responding Elastic Search:
goroutine 3433 [chan send]:
github.com/skydive-project/skydive/vendor/github.com/mattbaird/elastigo/lib.(*BulkIndexer).Index(0xc421e25e00, 0x1e0fdd2, 0x7, 0x1e08cec, 0x4, 0xc421b69620, 0x26, 0x0, 0x0, 0x0, ...)
	/home/stack/go/src/github.com/skydive-project/skydive/vendor/github.com/mattbaird/elastigo/lib/corebulk.go:287 +0x181
github.com/skydive-project/skydive/storage/elasticsearch.(*ElasticSearchClient).BulkIndex(0xc421e28800, 0x1e08cec, 0x4, 0xc421b69620, 0x26, 0x1b8f9a0, 0xc421b695f0, 0xc421b69620, 0x26)
	/home/stack/go/src/github.com/skydive-project/skydive/storage/elasticsearch/client.go:295 +0xd4
github.com/skydive-project/skydive/topology/graph.(*ElasticSearchBackend).createNode(0xc421d432f0, 0xc42389ac80, 0xc4246a3db0)
	/home/stack/go/src/github.com/skydive-project/skydive/topology/graph/elasticsearch.go:240 +0x11d
github.com/skydive-project/skydive/topology/graph.(*ElasticSearchBackend).NodeAdded(0xc421d432f0, 0xc42389ac80, 0xc42389ac80)
	/home/stack/go/src/github.com/skydive-project/skydive/topology/graph/elasticsearch.go:251 +0x35
github.com/skydive-project/skydive/topology/graph.(*CachedBackend).NodeAdded(0xc421d43380, 0xc42389ac80, 0xc4215c3788)
	/home/stack/go/src/github.com/skydive-project/skydive/topology/graph/cachedbackend.go:60 +0x162
github.com/skydive-project/skydive/topology/graph.(*Graph).AddNode(0xc421cf6f80, 0xc42389ac80, 0x24)
	/home/stack/go/src/github.com/skydive-project/skydive/topology/graph/graph.go:921 +0x42
github.com/skydive-project/skydive/topology/graph.(*Graph).NodeAdded(0xc421cf6f80, 0xc42389ac80, 0x24)
	/home/stack/go/src/github.com/skydive-project/skydive/topology/graph/graph.go:914 +0x72
github.com/skydive-project/skydive/analyzer.(*TopologyServer).OnWSJSONMessage(0xc4200c5e40, 0x2e210e0, 0xc423955240, 0xc421fe99c0)
	/home/stack/go/src/github.com/skydive-project/skydive/analyzer/topology_server.go:382 +0x731
github.com/skydive-project/skydive/http.(*wsJSONSpeakerEventDispatcher).dispatchMessage(0xc42169f3a0, 0xc423955240, 0xc421fe99c0)
	/home/stack/go/src/github.com/skydive-project/skydive/http/wsjson.go:157 +0x28c
github.com/skydive-project/skydive/http.(*WSJSONSpeaker).OnMessage(0xc423955240, 0x2e210e0, 0xc423955240, 0x2e00b80, 0xc4254021a0)
	/home/stack/go/src/github.com/skydive-project/skydive/http/wsjson.go:287 +0x4e6
github.com/skydive-project/skydive/http.(*WSConn).run(0xc422270460)
	/home/stack/go/src/github.com/skydive-project/skydive/http/wsclient.go:306 +0x7fc
created by github.com/skydive-project/skydive/http.(*WSConn).start
	/home/stack/go/src/github.com/skydive-project/skydive/http/wsclient.go:256 +0x5f

Possible resolving: making asynch connection with ElasticSearch

**Comment by safchain** [comment]
ElasticSearch is already working in async way, but the chan size may be to short

**Comment by safchain** [comment]
I guess this line should be configurable https://github.com/safchain/elastigo/blob/master/lib/corebulk.go#L111

**Comment by eranra** [comment]
I would advice we add some async mechanism (go channel ?)  in the persistent storage level as part of skydive,  releasing the graph semaphore quickly without any connection to the implementation of the specific storage backend. We now have some back-ends, but this is plagable so we might get others with other implementations

Bye the way, it is a consumer-producer thing, so there is no number we can bump in the elastic-search client to sustain for long time if the amount of data we create with skydive is above the ability of ewlastic to consume. 

With such channel in skydive code, we can decide to drop messages when we are 'out of channel space' and in any event since the effect of this issue was so critical (we get disconnects from agents and GUI, and this effects the entire stability of the Analyzer,) I really think it make sense to make sure we do not get to such situations.

**Comment by safchain** [comment]
I'm quite OK to put something within skydive, but we need to add a policy for the dropping part as we can't drop graph events but it might be OK for flows

**Comment by safchain** [comment]
I would start by increasing internal buffer of elasticsearch library in order to check limits as we already have an async mechanism even if this is not within Skydive. The goal here is to evaluate the benefits/impacts of a such mechanism.

**Comment by safchain** [comment]
I did some test and submitted some patches that helps quite a lot

#635
#643 
#645 

I never got disconnected even generating lot of flows. I did test it with flow over websocket and over UDP. I definitely got better performances over UDP. I think this because it uses two connections instead of one.

**Comment by safchain** [comment]
Closing it for now as #758 merged, will re-open if needed
